### ISSUE TITLE
Proposal to put Arc theme forward as standard

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Themes#2]
The least amount spend in maintaining themes and updating themes each time gtk changes again is my preferences because I do not have the expertise.
I do have 'some' expertise in understanding how to work with the arc theme. 

Together with me and Etles team I think we can make our own (ligt/dark/darker) theme.

We have etles team that can help out and they have helped out already by designing a theme from Arc.
[https://www.dropbox.com/s/wf584doc00z8rd8/AOB-Theme.zip?dl=0](https://www.dropbox.com/s/wf584doc00z8rd8/AOBTheme.zip?dl=0) 
![aob](https://cloud.githubusercontent.com/assets/10594806/23965512/7aaecbe2-09b8-11e7-9361-ce8d4965b385.png)

**Comment by Dobbie03** [comment]
Hi Erik, please proceed and let's see what you come up with.

**Comment by erikdubois** [comment]
documented elsewhere
[https://github.com/ARCHLabs/archlabs-arc-themes](https://github.com/ARCHLabs/archlabs-arc-themes)
